language: node_js
node_js:
  - "8.10.0"
branches:
  only:
  - develop
before_install:
  - npm i -g npm@3.5.2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov npm test
after_success: 
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
